blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/uct-masha/DTPBoost/blob/main/README.md
    about: Please check the README and documentation first
  - name: Contributing Guidelines
    url: https://github.com/uct-masha/DTPBoost/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project